FROM python:3.11-slim
WORKDIR /app
COPY api/requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt
COPY api /app
ENV FLASK_ENV=production
EXPOSE 9090
CMD ["gunicorn", "--bind", "0.0.0.0:9090", "app:app", "--workers", "2"]
